# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isharonline', '0002_meditations'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditations',
            name='AbstractNote',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Author',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='AutomaticTags',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='DOI',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Date',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='DateAdded',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='DateModified',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Extra',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='ISSN',
            field=models.CharField(default=None, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Issue',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='ItemType',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='JournalAbbreviation',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Key',
            field=models.CharField(default=None, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Language',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='LibraryCatalog',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='LinkAttachment',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Pages',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Publication',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='PublicationTitle',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='ShortTitle',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditations',
            name='Title',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
