# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isharonline', '0004_auto_20171028_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditations',
            name='AbstractNote',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meditations',
            name='Date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='meditations',
            name='DateAdded',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meditations',
            name='DateModified',
            field=models.DateField(max_length=50),
        ),
    ]
